name : Check branch name      # describes what you want to do
on : [push]                   # when should job run ?

jobs :
  branch_name :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
      - name : Branch Name
        run : |
          echo 'Name of this branch is ' ${{github.ref_name}}
